# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

keybindings: vi 
editor: nvim
model: duskadiy:Qwen3-Coder-30B-Instruct-IQ4_XS
clients:
- type: openai-compatible
  name: local
  api_base: http://192.168.0.204:11343/v1
  models:
  - name: Qwen3.5-27B-UD-Q3_K_XL
  - name: Qwen3.5-9B-Q8_0
  - name: Qwen3-Coder-30B-Instruct-IQ4_XS
  - name: GLM-4.7-Flash-UD-Q3_K_XL
  - name: DeepSeek-Coder-V2-Lite-Instruct-Q8_0
  - name: gemma-4-E4B-it-UD-Q8_K_XL
  - name: gemma-4-26B-A4B-it-UD-IQ4_XS
- type: openai-compatible
  name: duskadiy
  api_base: https://llm.duskadiy.com/api/v1
  models:
  - name: Qwen3.5-27B-UD-Q3_K_XL
  - name: Qwen3.5-9B-Q8_0
  - name: Qwen3-Coder-30B-Instruct-IQ4_XS
  - name: GLM-4.7-Flash-UD-Q3_K_XL
  - name: DeepSeek-Coder-V2-Lite-Instruct-Q8_0
  - name: gemma-4-E4B-it-UD-Q8_K_XL
  - name: gemma-4-26B-A4B-it-UD-IQ4_XS
