# run with `kitty --session ~/.config/kitty/c2.conf`

# create a new tab
new_tab c2

cd ~/projects/wingman/wm-clients/c2/c2-main/
launch --var window=first nvim
# open the session focused on nvim
focus

new_tab git

cd ~/projects/wingman/wm-clients/c2/c2-main/
launch --var window=second lazygit
