# run with `kitty --session ~/.config/kitty/runners.conf`

##### TAB Logs #####
new_tab logs
layout splits

cd ~/projects/wingman/wm-clients/c2/c2-main/

# --hold keeps the window open if the process crashes
launch --var window=first --hold pnpm dev

launch --location=hsplit lazydocker
# resize_window wider 120


##### TAB Runners #####
new_tab runners
layout splits

launch --var window=first react-devtools

cd ~/software/wmclient/

launch --location=hsplit --hold ./wmsimulator.sh
resize_window taller 120
