modmap:
  - name: CapsLock to LeftCtrl/Esc
    remap:
      CapsLock:
        held: leftctrl 
        alone: esc
        alone_timeout_millis: 150
# keymap:
#   - name: Alt+hjkl to Arrows
#     remap:
#       Alt-h: left
#       Alt-l: right
#       Alt-j: down
#       Alt-k: up
#       Alt-u: pageup
#       Alt-d: pagedown
# keymap:
#   - name: Freetube remap
#    application: 
#     only: FreeTube
#     remap:
#       Alt-h: Left
#       Alt-l: Right
#       Alt-j: Down
#       Alt-k: Up
