#! █░█ █▄█ █▀█ █▀█ █░░ █▀█ █▀▀ █▄▀
#! █▀█ ░█░ █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █░█

#*  Hyprlock Configuration File 

$fontColor = rgba(255,255,255,0.5)
$fontFamily = SourceCodeVF ExtraBold
$timeFontFamily = Cantarell ExtraBold

general {
  no_fade_in = true
  grade = 1
  ignore_empty_input = true
  text_trim = true
  fade_in_time = 0.8
  disable_loading_bar = 0
}

background {
  monitor = 
  path = ~/sync/Drive/pics/foss-world-crop.png
  blur_passes = 2
  blur_size = 4
  contrast = 0.7
  brightness = 0.3
  vibrancy = 0.15
  vibrancy_darkness = 0.5
}

image {
  monitor = 
  path = ~/sync/Drive/pics/matrixom-crop.png
  position = 0, 80
  reload_time = -1
  reload_cmd =
}

input-field {
  monitor =
  size = 20%, 5%
  position = 0, -60
  outline_thickness = 3
  dots_size = 0.08
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgba(0,0,0,0.1)
  inner_color = $fontColor
  fade_on_empty = true
}

label {
  monitor =
  text = cmd[update:5000] echo "<span alpha='40%'>$(uptime -p)</span>"
  color = $fontColor
  font_family = $fontFamily
  font_size = 15
  position = 0, 350
}

label {
  monitor =
  text = cmd[update:300000] echo "<span alpha='50%'>$(cat ~/.config/fish/greet.txt)</span>"
  color = $fontColor
  font_family = $fontFamily
  font_size = 14
  position = 0, 310
}

label {
  monitor =
  text = cmd[update:1000] echo "<span alpha='50%'>$(date +"%H:%M")</span>"
  color = $fontColor
  font_family = $timeFontFamily
  font_size = 120
  position = 0, -180
  animation = pulse 2s infinite
  opacity = 0.5
  shadow_passes = 1
  shadow_size = 1
  shadow_color = rgba(0, 0, 0, 0.5)
}

label {
  monitor =
  text = cmd[update:1000] echo "<span alpha='50%'>$(LC_TIME=en_US.UTF-8 date +'%A, %B %d')</span>"
  color = $fontColor
  font_family = $fontFamily
  font_size = 25
  position = 0, -300
}

label {
  monitor =
  text = cmd[update:1000] echo -e "<span alpha='50%'>$(~/.config/hypr/battery.sh)</span>"
  color = $fontColor
  font_family = $fontFamily
  font_size = 14
  position = -50, 30
  halign = right
  valign = bottom
}

label {
  monitor = 
  color = $fontColor
  text = cmd[] echo "<span alpha='50%'>⏻ </span>"
  font_size = 24
  onclick = systemctl poweroff
  position = 50, 30
  halign = left
  valign = bottom
}




