# Synthwave '84 — matches ../kitty/theme.conf

[colors.primary]
background = "#262335"
foreground = "#ffffff"

[colors.cursor]
text = "#262335"
cursor = "#f97e72"

[colors.selection]
text = "#262335"
background = "#f97e72"

[colors.normal]
black = "#232530"
red = "#fe4450"
green = "#72f1b8"
yellow = "#ff7edb"
blue = "#03edf9"
magenta = "#fede5d"
cyan = "#03edf9"
white = "#ffffff"

[colors.bright]
black = "#232530"
red = "#fe4450"
green = "#72f1b8"
yellow = "#ff7edb"
blue = "#03edf9"
magenta = "#f3e70f"
cyan = "#03edf9"
white = "#ffffff"
